/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaofeng_audiorecord_MainActivity */

#ifndef _Included_com_xiaofeng_audiorecord_MainActivity
#define _Included_com_xiaofeng_audiorecord_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT void JNICALL Java_com_xiaofeng_audiorecord_MainActivity_initWav
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_xiaofeng_audiorecord_MainActivity
 * Method:    onPcm
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_xiaofeng_audiorecord_MainActivity_onPcm
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
